package consts;

/**
 * Created by jaeyoung on 2017. 4. 13..
 */
public interface Consts {
    int BLACK_STONE = 1;
    int WHITE_STONE = -1;
    int NONE_STONE = 0;
    int WALL_STONE = WHITE_STONE;

    int X = 0;
    int Y = 1;

    interface Directions {
        int[] UP = {0, -1};
        int[] RIGHT_UP = {1, -1};
        int[] RIGHT = {1, 0};
        int[] RIGHT_DOWN = {1, 1};
        int[] DOWN = {0, 1};
        int[] LEFT_DOWN = {-1, 1};
        int[] LEFT = {-1, 0};
        int[] LEFT_UP = {-1, -1};
    }

    // GUI Coordinates
    int XSTART = 20, YSTART = 20, CELLSIZE = 29;

    int HUMAN_PLAYER = 0;
    int AI_PLAYER = 1;

    int VICTORY = 1;

    // Evaluation
    float INF = 10000.0f;
    float ZERO = 0f;
    float FOUR_SEQ = 1000.0f;
    float THREE_SEQ = 100.0f;
    float TWO_SEQ = 10.0f;
    float ONE_SEQ = 1.0f;
    float ZERO_SEQ = 0.1f;

    // Eval Sequence
    //  11111 INF Score1
    String AA = ""+BLACK_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE;
    float AA_SCORE = INF;
    //  011110 INF Score1000
    String AB = ""+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE;
    float AB_SCORE = INF;

    // -111110 4R Score1000
    String BA = ""+WHITE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE;
    String BAR = ""+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+WHITE_STONE;
    float BA_SCORE = FOUR_SEQ;

    //  0011100 3 Score100
    String CA = ""+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE;
    float CA_SCORE = THREE_SEQ;
    // -1011100 3R
    String CB = ""+WHITE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE;
    String CBR = ""+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+WHITE_STONE;
    float CB_SCORE = THREE_SEQ-TWO_SEQ;
    // -111100 3R
    String CC = ""+WHITE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE;
    String CCR = ""+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+BLACK_STONE+WHITE_STONE;
    float CC_SCORE = THREE_SEQ-TWO_SEQ*2;


    // 00011000 2 Score10
    String DA = ""+NONE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    float DA_SCORE = TWO_SEQ;
    // -10011000 2R
    String DB = ""+WHITE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String DBR = ""+NONE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float DB_SCORE = TWO_SEQ-ONE_SEQ;

    // -1011000 2R
    String DC = ""+WHITE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String DCR = ""+NONE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+WHITE_STONE;
    float DC_SCORE = TWO_SEQ-ONE_SEQ*2;
    // -111000 2R
    String DD = ""+WHITE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String DDR = ""+NONE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+WHITE_STONE;
    float DD_SCORE = TWO_SEQ-ONE_SEQ*3;

    // -1001100-1 2
    String DE = ""+WHITE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float DE_SCORE = TWO_SEQ-ONE_SEQ*4;
    // -100110-1 2R
    String DF = ""+WHITE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+WHITE_STONE;
    String DFR = ""+WHITE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float DF_SCORE = TWO_SEQ-ONE_SEQ*5;
    // -101100-1 2R
    String DG = ""+WHITE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    String DGR = ""+WHITE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+BLACK_STONE+NONE_STONE+WHITE_STONE;
    float DG_SCORE = TWO_SEQ-ONE_SEQ*6;

    // 000010000 Score1
    String EA = ""+NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    float EA_SCORE = ONE_SEQ;
    // -100010000
    String EB = ""+WHITE_STONE +NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String EBR = ""+NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float EB_SCORE = ONE_SEQ-ZERO_SEQ;

    // -10010000
    String EC = ""+WHITE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String ECR = ""+NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+WHITE_STONE;
    float EC_SCORE = ONE_SEQ-ZERO_SEQ*2;
    // -1010000
    String ED = ""+WHITE_STONE +NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String EDR = ""+NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+WHITE_STONE;
    float ED_SCORE = ONE_SEQ-ZERO_SEQ*3;
    // -110000
    String EE = ""+WHITE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE;
    String EER = "" +NONE_STONE+NONE_STONE+NONE_STONE+NONE_STONE+BLACK_STONE+WHITE_STONE;
    float EE_SCORE = ONE_SEQ-ZERO_SEQ*4;

    // -10001000-1
    String EF = ""+WHITE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float EF_SCORE = ONE_SEQ-ZERO_SEQ*5;
    // -1000100-1
    String EG = ""+WHITE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+WHITE_STONE;
    String EGR = ""+WHITE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float EG_SCORE = ONE_SEQ-ZERO_SEQ*5;
    // -100010-1
    String EH = ""+WHITE_STONE +NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+WHITE_STONE;
    String EHR = ""+WHITE_STONE +NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE+WHITE_STONE;
    float EH_SCORE = ONE_SEQ-ZERO_SEQ*5;

    // -1001000-1
    String EI = ""+WHITE_STONE +NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE +WHITE_STONE;
    String EIR = ""+WHITE_STONE +NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+WHITE_STONE;
    float EI_SCORE = ONE_SEQ-ZERO_SEQ*5;
    // -100100-1
    String EJ = ""+WHITE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +NONE_STONE+NONE_STONE+ WHITE_STONE;
    float EJ_SCORE = ONE_SEQ-ZERO_SEQ*5;

    // -101000-1
    String EK = ""+WHITE_STONE+ NONE_STONE+ BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE +WHITE_STONE;
    String EKR = ""+WHITE_STONE+ NONE_STONE+NONE_STONE +NONE_STONE+ BLACK_STONE +NONE_STONE+WHITE_STONE;
    float EK_SCORE = ONE_SEQ-ZERO_SEQ*5;

    // -10001-1
    String EL = ""+WHITE_STONE+NONE_STONE+NONE_STONE+NONE_STONE +BLACK_STONE +WHITE_STONE;
    String ELR = ""+WHITE_STONE+BLACK_STONE +NONE_STONE+NONE_STONE+NONE_STONE +WHITE_STONE;
    float EL_SCORE = ONE_SEQ-ZERO_SEQ*5;
}
